# Use miniconda with Python 3.13
FROM docker.io/continuumio/miniconda3:25.3.1-1

# Stop container's bash from leaving .bash_histories everywhere
# and add convenience aliases for interactive (debugging) use
RUN echo "unset HISTFILE" >>/etc/bash.bashrc && \
    echo "alias ls='ls --color=auto' l='ls -CF' la='l -a' ll='l -l' lla='ll -a'" >>/etc/bash.bashrc

# Conda installable
# ----------------------------------------------------------------------

RUN conda install -c conda-forge -c bioconda -c nodefaults --quiet --yes ncbi-amrfinderplus=4.0.23 && \
    conda clean -qafy

# Ubuntu dependencies
# ----------------------------------------------------------------------

# AFP fails to index its database without libmpi40
RUN apt-get -qq update && apt-get -qq install libopenmpi-dev && \
    apt-get -qq clean && \
    rm -rf /var/lib/apt/lists/*

# Install Database in the container
# ----------------------------------------------------------------------

RUN mkdir /database && \
    amrfinder_update -d /database && \
    ln -srfT `realpath /database/latest` /database/latest

# AFP doesn't need -d argument when this envvar is set
ENV AMRFINDER_DB /database/latest

# AFP warns (probably harmless) that this should be set
ENV CONDA_PREFIX /opt/conda

# Install amrfinderplus wrapper script (no longer needed since ENV)
# ----------------------------------------------------------------------

RUN printf '#!/bin/sh\nexec amrfinder "$@"' \
    >/usr/local/bin/amrfinderplus && \
    chmod +x /usr/local/bin/amrfinderplus

# Default command
#----------------------------------------------------------------------

# No ENTRYPOINT means that any binary on the PATH in the container can
# be run.  Set CMD so that without arguments, user gets AFP --help.
CMD ["echo", "Usage: amrfinderplus -n FASTA -O SPECIES -o FILE [--threads N]"]

